import { ArrowRight, BadgeCheck, Building2, ClipboardCheck, FileSearch, Landmark, ShieldCheck } from 'lucide-react'
import { Link } from 'react-router-dom'

const features = [
  ['Inspection Management', 'Create and manage digital inspection records.', ClipboardCheck], ['Product & Business Management', 'Maintain business and product information.', Building2], ['Label & OCR Analysis', 'Analyze uploaded labels and extract relevant declarations.', FileSearch], ['Compliance Checking', 'Review extracted information against configured requirements.', ShieldCheck], ['Laboratory Management', 'Manage samples and laboratory reports associated with inspections.', Landmark], ['Violation Management', 'Record and track potential and confirmed non-compliances.', BadgeCheck], ['Digital Reports', 'Generate digital inspection and compliance reports.', FileSearch], ['Search & History', 'Search previous inspections, products, businesses, and reports.', FileSearch], ['Dashboard', 'Monitor inspections, compliance information, and violations.', ClipboardCheck],
] as const
const steps = ['Business / Product', 'Inspection', 'Upload Label / Package Image', 'OCR & Data Extraction', 'Applicable Requirements', 'Compliance Checking', 'Officer Verification', 'Optional Sample & Laboratory Testing', 'Final Inspection Result', 'Digital Report', 'Search & Dashboard']

export function AboutSection() { return <section className="section about-section" id="about"><div className="section-kicker">A clearer record of every inspection</div><div className="about-grid"><div><h2>One dependable workspace for field and office teams.</h2></div><div><p>The system assists Legal Metrology authorities in managing inspections and reviewing packaged commodities against applicable legal requirements. It combines inspection records, product information, label analysis, compliance checks, laboratory records, violations, and digital reporting in one centralized platform.</p><p className="muted-note">The platform supports officer review and record keeping. Final legal determinations remain with the authorised department and its officers.</p></div></div></section> }
export function FeaturesSection() { return <section className="section" id="features"><div className="section-heading"><div><div className="section-kicker">Built around your workflow</div><h2>Everything in one record.</h2></div><p>Structured modules make it easier to move from a business visit to a complete, reviewable inspection record.</p></div><div className="feature-grid">{features.map(([title, description, Icon]) => <article className="feature-card" key={title}><div className="feature-icon"><Icon size={19} /></div><h3>{title}</h3><p>{description}</p><ArrowRight size={16} className="feature-arrow" /></article>)}</div></section> }
export function WorkflowSection() { return <section className="section workflow-section" id="workflow"><div className="section-heading"><div><div className="section-kicker">A connected process</div><h2>From package to report.</h2></div><p>Each stage adds context to the central inspection record, keeping review history clear and accessible.</p></div><div className="workflow-grid">{steps.map((step, index) => <div className="workflow-step" key={step}><span>{String(index + 1).padStart(2, '0')}</span><strong>{step}</strong>{index < steps.length - 1 && <i />}</div>)}</div></section> }
export function ServicesSection() { const services = [['Certificate Verification', 'Check certificate records when public access is available.'], ['Application Status', 'Follow the progress of an application or request.'], ['Complaint / Grievance', 'Share an issue with the appropriate department.'], ['Public Information', 'Find guidance and public Legal Metrology information.']] as const; return <section className="section services-section" id="services"><div className="section-heading"><div><div className="section-kicker">Public access</div><h2>Services for everyone.</h2></div></div><div className="service-grid">{services.map(([title, description]) => <Link to="/public-services" className="service-card" key={title}><div><h3>{title}</h3><p>{description}</p></div><ArrowRight size={18} /></Link>)}</div></section> }
