import { FormEvent, useEffect, useState } from 'react'
import { ArrowLeft, ArrowRight, CheckCircle2, KeyRound, Mail, ShieldCheck } from 'lucide-react'
import { Link, useLocation, useNavigate } from 'react-router-dom'
import { getDemoAccounts, useAuth } from '../context/AuthContext'
import { roleLabels, type Role } from '../types/auth'

function homeForRole(role: Role | undefined) {
  if (role === 'super_admin') return '/dashboard/admin'
  if (role === 'controller') return '/dashboard/controller'
  if (role === 'assistant_controller') return '/dashboard/assistant-controller'
  if (role === 'inspector') return '/dashboard/inspector'
  if (role === 'clerk') return '/dashboard/clerk'
  if (role === 'laboratory_user') return '/dashboard/laboratory'
  if (role) return '/dashboard/business'
  return '/dashboard'
}

function AuthFrame({ title, description, children }: { title: string; description: string; children: React.ReactNode }) {
  return <div className="auth-page"><div className="auth-card"><Link className="public-brand" to="/"><span className="brand-mark"><ShieldCheck size={19} /></span><span><strong>Legal Metrology</strong><small>Compliance & inspection</small></span></Link><div className="auth-heading"><p className="section-kicker">Secure access</p><h1>{title}</h1><p>{description}</p></div>{children}</div></div>
}

function AuthError({ message }: { message: string | null }) { return message ? <div className="auth-alert auth-alert-error">{message}</div> : null }
function Input({ label, type = 'text', value, onChange, placeholder, required = true }: { label: string; type?: string; value: string; onChange: (value: string) => void; placeholder?: string; required?: boolean }) { return <label className="form-field"><span>{label}</span><input type={type} value={value} required={required} placeholder={placeholder} onChange={(event) => onChange(event.target.value)} /></label> }

function DemoAccountsPanel({ type }: { type: 'government' | 'business' }) {
  const auth = useAuth(); const navigate = useNavigate(); const accounts = getDemoAccounts()
  if (!accounts.length || type !== 'government') return null
  return <div className="auth-demo-panel"><p className="section-kicker">Development sample users</p>{accounts.map((account) => <button key={account.key} type="button" className="button button-ghost demo-login-button" onClick={async () => { const result = await auth.signInDemo(account.key); if (!result.error) navigate('/dashboard', { replace: true }) }}>{account.label}<ArrowRight size={15} /></button>)}</div>
}

export function LoginFormPage({ type }: { type: 'government' | 'business' }) {
  const auth = useAuth(); const navigate = useNavigate(); const location = useLocation()
  const [email, setEmail] = useState(''); const [otp, setOtp] = useState(''); const [sent, setSent] = useState(false); const [cooldown, setCooldown] = useState(0); const [submitting, setSubmitting] = useState(false); const [message, setMessage] = useState<string | null>(null)
  const from = (location.state as { from?: string } | null)?.from
  const send = async () => { setSubmitting(true); setMessage(null); const result = await auth.sendOtp(email); setSubmitting(false); if (result.error) setMessage(auth.error ?? 'Unable to send the verification code.'); else { setSent(true); setCooldown(60) } }
  const submit = async (event: FormEvent) => { event.preventDefault(); if (!sent) { await send(); return }; setSubmitting(true); setMessage(null); const result = await auth.verifyOtp(email, otp); setSubmitting(false); if (result.error) setMessage(auth.error ?? 'The verification code is invalid or expired.'); else navigate(from ?? homeForRole(auth.profile?.role), { replace: true }) }
  useEffect(() => { if (cooldown <= 0) return; const timer = window.setInterval(() => setCooldown((value) => Math.max(0, value - 1)), 1000); return () => window.clearInterval(timer) }, [cooldown])
  return <AuthFrame title={type === 'government' ? 'Department login' : 'Business login'} description={type === 'government' ? 'Sign in with your authorised Legal Metrology email.' : 'Sign in to manage your business records and applications.'}><form className="auth-form" onSubmit={submit}><AuthError message={message ?? auth.error} /><Input label="Email address" type="email" value={email} onChange={setEmail} placeholder="name@organisation.gov" /><p className="form-help">We will send a one-time 6-digit verification code. Passwords are never stored by this application.</p>{sent && <Input label="6-digit verification code" value={otp} onChange={(value) => setOtp(value.replace(/\D/g, '').slice(0, 6))} placeholder="000000" />}<div className="form-row">{sent && <button className="back-link" type="button" disabled={cooldown > 0 || submitting} onClick={() => void send()}>{cooldown > 0 ? `Resend in ${cooldown}s` : 'Resend code'}</button>}<Link to="/forgot-password">Password reset</Link></div><button className="button button-dark auth-submit" disabled={submitting || (sent && otp.length !== 6)}>{submitting ? (sent ? 'Verifying...' : 'Sending...') : sent ? 'Verify code' : 'Send verification code'} <ArrowRight size={16} /></button></form>{type === 'business' && <p className="auth-footer-copy">Need an account? <Link to="/register/business">Apply for business access</Link></p>}<Link className="back-link" to="/login"><ArrowLeft size={14} /> Choose another login</Link>{!auth.configured && <div className="auth-alert auth-alert-info">Supabase is not configured for this environment.</div>}<DemoAccountsPanel type={type} /></AuthFrame>
}

export function BusinessRegistrationPage() { const auth = useAuth(); const [form, setForm] = useState({ fullName: '', email: '', phone: '', businessName: '', businessType: 'manufacturer', registrationNumber: '', address: '', state: '', district: '', password: '' }); const [submitted, setSubmitted] = useState(false); const [message, setMessage] = useState<string | null>(null); const update = (key: keyof typeof form) => (value: string) => setForm((current) => ({ ...current, [key]: value })); const submit = async (event: FormEvent) => { event.preventDefault(); const result = await auth.signUpBusiness(form); if (result.error) setMessage(auth.error ?? 'We could not submit the application.'); else setSubmitted(true) }; if (submitted) return <AuthFrame title="Application received" description="Your business access request has been submitted for review."><div className="success-block"><CheckCircle2 size={36} /><p>Your account is pending approval. We will contact you at <strong>{form.email}</strong>.</p><Link className="button button-dark" to="/login/business">Return to login</Link></div></AuthFrame>; return <AuthFrame title="Apply for business access" description="Create a business account application. Access remains pending until approved."><form className="auth-form registration-form" onSubmit={submit}><AuthError message={message} /><div className="form-two-col"><Input label="Full name" value={form.fullName} onChange={update('fullName')} /><Input label="Email" type="email" value={form.email} onChange={update('email')} /><Input label="Phone" value={form.phone} onChange={update('phone')} /><Input label="Business name" value={form.businessName} onChange={update('businessName')} /><Input label="Registration number" value={form.registrationNumber} onChange={update('registrationNumber')} /><Input label="Address" value={form.address} onChange={update('address')} /><Input label="State" value={form.state} onChange={update('state')} /><Input label="District" value={form.district} onChange={update('district')} /><Input label="Password" type="password" value={form.password} onChange={update('password')} /></div><div className="form-actions"><Link className="button button-ghost" to="/login/business">Cancel</Link><button className="button button-primary" type="submit">Submit application</button></div></form></AuthFrame> }
export function ForgotPasswordPage() { const auth = useAuth(); const [email, setEmail] = useState(''); const [sent, setSent] = useState(false); const [message, setMessage] = useState<string | null>(null); const submit = async (event: FormEvent) => { event.preventDefault(); const result = await auth.sendPasswordReset(email); if (result.error) setMessage(auth.error ?? 'Unable to send reset email.'); else setSent(true) }; return <AuthFrame title="Reset your password" description="Enter your email and we will send a secure password reset link.">{sent ? <div className="success-block"><Mail size={36} /><p>Check your inbox for the password reset link.</p><Link className="button button-dark" to="/login">Return to login</Link></div> : <form className="auth-form" onSubmit={submit}><AuthError message={message} /><Input label="Email address" type="email" value={email} onChange={setEmail} /><button className="button button-dark auth-submit">Send reset link <ArrowRight size={16} /></button></form>}<Link className="back-link" to="/login"><ArrowLeft size={14} /> Return to login</Link></AuthFrame> }
export function ResetPasswordPage() { const auth = useAuth(); const navigate = useNavigate(); const [password, setPassword] = useState(''); const [message, setMessage] = useState<string | null>(null); const submit = async (event: FormEvent) => { event.preventDefault(); const result = await auth.updatePassword(password); if (result.error) setMessage(auth.error ?? 'Unable to update password.'); else navigate('/dashboard', { replace: true }) }; return <AuthFrame title="Choose a new password" description="Use a strong password that you do not reuse elsewhere."><form className="auth-form" onSubmit={submit}><AuthError message={message} /><Input label="New password" type="password" value={password} onChange={setPassword} /><button className="button button-dark auth-submit">Update password <KeyRound size={16} /></button></form></AuthFrame> }
export function AccountStatePage({ state }: { state: 'denied' | 'inactive' | 'pending' }) { const config = state === 'denied' ? { title: 'Access denied', description: 'You do not have permission to access this page.', icon: ShieldCheck } : state === 'inactive' ? { title: 'Account inactive', description: 'Your account is currently inactive. Please contact the administrator.', icon: ShieldCheck } : { title: 'Account pending', description: 'Your business account is awaiting approval.', icon: CheckCircle2 }; const Icon = config.icon; return <AuthFrame title={config.title} description={config.description}><div className="success-block"><Icon size={38} /><p>{config.description}</p><Link className="button button-dark" to="/">Return to public site</Link></div></AuthFrame> }
export function ProfilePage() { const auth = useAuth(); const profile = auth.profile; return <AuthFrame title="My profile" description="Your identity and organization details are managed through your authorized account."><div className="profile-summary"><div className="avatar avatar-large">{profile?.full_name.slice(0, 2).toUpperCase()}</div><h2>{profile?.full_name}</h2><span className="role-badge">{profile && roleLabels[profile.role]}</span><p>{profile?.email}</p><p>{profile?.user_type === 'government' ? 'Legal Metrology Office' : 'Business account'}</p></div><Link className="back-link" to="/dashboard"><ArrowLeft size={14} /> Back to workspace</Link></AuthFrame> }
