import { BookOpen, CheckCircle2, Database, FileText, GitBranch, LockKeyhole, Server, ShieldCheck } from 'lucide-react'
import { Link } from 'react-router-dom'
import { EmptyState, PageHeader } from '../components/common/Ui'

const steps = ['Authentication', 'Role & access', 'Office / business', 'Product', 'Inspection', 'Evidence', 'OCR', 'Compliance', 'Officer verification', 'Sample', 'Laboratory', 'Violation', 'Report', 'Notification', 'Search / history', 'Audit', 'Analytics']
const modules = [
  ['Authentication', 'Implemented / pending hosted test', 'Supabase email OTP, session restore, profile status checks.'],
  ['Inspection management', 'Implemented / pending hosted test', 'Inspection is the central record and connects office, inspector, business, and product.'],
  ['OCR', 'Implemented / Demo boundary', 'Replaceable OCR service boundary with explicit demo/mock fallback and review states.'],
  ['Compliance engine', 'Implemented / pending hosted test', 'Versioned database rules produce preliminary checks; officers make final decisions.'],
  ['Laboratory', 'Implemented / pending hosted test', 'Samples, custody, tests, results, and laboratory reports use scoped records.'],
  ['Reports', 'Implemented / pending hosted test', 'Snapshot-backed PDF/DOCX generation with version and approval state.'],
  ['Notifications', 'Implemented / pending hosted test', 'Recipient-scoped database notifications with read state.'],
  ['Search, history, audit', 'Implemented / pending hosted test', 'Database-backed search and audit history constrained by RLS.'],
  ['Hosted deployment checks', 'Pending', 'Run migrations, OTP delivery, RLS, storage, and role smoke tests in Supabase.'],
]

function DocsShell({ title, eyebrow, description, children }: { title: string; eyebrow: string; description: string; children: React.ReactNode }) { return <><PageHeader eyebrow={eyebrow} title={title} description={description} /><div className="documentation-content">{children}</div></> }
function DocCard({ icon: Icon, title, children }: { icon: React.ElementType; title: string; children: React.ReactNode }) { return <section className="detail-card documentation-card"><div className="detail-card-heading"><Icon size={20} /><div><h2>{title}</h2></div></div>{children}</section> }

export function HelpPage() { return <DocsShell eyebrow="User guide" title="Help and workflows" description="Simple guidance for using the inspection-support platform."><div className="documentation-grid"><DocCard icon={BookOpen} title="Government users"><ol><li>Sign in with your authorized email and OTP.</li><li>Open Dashboard, then select a business and product.</li><li>Create an inspection, assign the inspector, and upload evidence.</li><li>Run OCR and review extracted fields and confidence.</li><li>Run compliance rules, then record an officer decision.</li><li>Create samples, follow laboratory status, and review results.</li><li>Create a violation only after confirmed officer non-compliance.</li><li>Generate, review, approve, and download the report.</li></ol></DocCard><DocCard icon={Server} title="Laboratory users"><ol><li>Open Assigned Samples and verify receipt and custody.</li><li>Create or accept assigned tests.</li><li>Enter results with method and observations.</li><li>Generate the laboratory report for review.</li></ol></DocCard><DocCard icon={FileText} title="Business users"><ol><li>Review your business profile and products.</li><li>View permitted inspection and compliance information.</li><li>Review reports shared with your business.</li><li>Submit corrective action when requested.</li></ol></DocCard></div><DocCard icon={ShieldCheck} title="Important principle"><p>OCR and automated rules assist the inspection process. They never independently establish a legal violation. Only an authorized officer can make the final compliance decision.</p></DocCard></DocsShell> }

export function ProjectInfoPage() { return <DocsShell eyebrow="Project information" title="Legal Metrology Compliance & Inspection Management System" description="A secure, role-based platform supporting inspection, compliance verification, laboratory workflows, violation management, reporting, notifications, and historical records."><DocCard icon={CheckCircle2} title="Implemented technologies"><p>React, TypeScript, Vite, React Router, Supabase Auth, PostgreSQL, Supabase Storage, email OTP authentication, PDF/DOCX generation, and a modular OCR/Tesseract service boundary.</p><p>Tailwind CSS is present in the project configuration. A separate shadcn/ui component package is not currently used, so it is not claimed as an implemented dependency.</p></DocCard><DocCard icon={GitBranch} title="Connected workflow"><div className="workflow-strip">{steps.map((step, index) => <span key={step}>{index > 0 && <b>→</b>}{step}</span>)}</div></DocCard></DocsShell> }

export function ArchitecturePage() { return <DocsShell eyebrow="Technical documentation" title="System architecture" description="The application keeps identity, authorization, records, storage, and service boundaries explicit."><DocCard icon={Server} title="Request path"><pre className="architecture-diagram">{`Users\n  ↓\nReact + TypeScript frontend\n  ↓\nSupabase Authentication\n  ↓\nSupabase API / Edge Functions\n  ↓\nPostgreSQL + RLS\n  ↓\nPrivate Supabase Storage\n\nModular services: OCR boundary · PDF/DOCX reports · notifications`}</pre></DocCard><DocCard icon={LockKeyhole} title="Security layer"><p>RLS, role-based access, office and business scope checks, private storage policies, audit logging, input validation, OTP rate limits, session restoration, and secure logout protect the workflow. Frontend permissions are usability controls; database policies are the authorization boundary.</p></DocCard></DocsShell> }

export function SystemStatusPage() { return <DocsShell eyebrow="Administrator view" title="System status" description="Status is based on repository implementation. Hosted Supabase checks remain pending until executed against the deployment project."><div className="status-module-grid">{modules.map(([name, status, note]) => <article className="status-module" key={name}><div><CheckCircle2 size={18} /><strong>{name}</strong></div><span className={status === 'Pending' ? 'status-pending' : 'status-operational'}>{status}</span><p>{note}</p></article>)}</div><div className="module-panel"><EmptyState icon={Database} title="Deployment verification required" description="Apply migrations and run OTP, RLS, storage, role, and responsive smoke tests against the target Supabase project before marking deployment complete." action="See DEPLOYMENT.md" /></div></DocsShell> }

export function DeploymentChecklistPage() { return <DocsShell eyebrow="Release checklist" title="Deployment checklist" description="Use this checklist before a demonstration or production release."><DocCard icon={Database} title="Backend"><ul className="checklist"><li>Supabase project configured</li><li>All migrations applied in order</li><li>RLS and private storage policies tested</li><li>Edge Functions deployed and authorized</li><li>Email OTP provider and redirect URLs configured</li></ul></DocCard><DocCard icon={ShieldCheck} title="Frontend and security"><ul className="checklist"><li>Only safe VITE_* variables are configured</li><li>Production build succeeds</li><li>Demo login is disabled in production</li><li>Role URLs and business isolation tested</li><li>No service-role key is exposed to the browser</li></ul></DocCard><p className="form-help">See <Link to="/architecture">Architecture</Link> and the repository <strong>docs/DEPLOYMENT.md</strong> for the complete release procedure.</p></DocsShell> }
