import { AlertTriangle, Bell, Building2, ClipboardCheck, FileBarChart, FileSearch, FlaskConical, History, Package, ScanLine, Search, Settings, ShieldCheck, Store, Users } from 'lucide-react'
import { Link } from 'react-router-dom'
import { DataTable } from '../components/common/DataTable'
import { EmptyState, FilterBar, PageHeader, SearchBar, StatusBadge } from '../components/common/Ui'
import { StatCard } from '../components/common/StatCard'

const moduleConfig: Record<string, { title: string; description: string; icon: React.ElementType; action?: string }> = {
  offices: { title: 'Offices', description: 'Manage government offices and their inspection jurisdictions.', icon: Building2, action: 'Add Office' },
  officers: { title: 'Officers', description: 'Maintain authorised officers, roles, and office assignments.', icon: Users, action: 'Add Officer' },
  businesses: { title: 'Businesses', description: 'Maintain manufacturer, packer, importer, dealer, and retailer records.', icon: Store, action: 'Add Business' },
  products: { title: 'Products', description: 'Maintain product profiles and packaged commodity information.', icon: Package, action: 'Add Product' },
  inspections: { title: 'Inspections', description: 'Create and manage Legal Metrology inspection records.', icon: ClipboardCheck, action: 'Create Inspection' },
  ocr: { title: 'OCR & Label Analysis', description: 'Review uploaded package labels and extracted declarations.', icon: ScanLine, action: 'Start Analysis' },
  compliance: { title: 'Compliance', description: 'Review requirement checks linked to inspection records.', icon: ShieldCheck, action: 'Open Review Queue' },
  samples: { title: 'Samples & Laboratory', description: 'Track samples and laboratory records associated with inspections.', icon: FlaskConical, action: 'Register Sample' },
  laboratory: { title: 'Laboratory', description: 'Manage laboratory reports and testing records.', icon: FlaskConical, action: 'Add Report' },
  violations: { title: 'Violations', description: 'Record and track potential and confirmed non-compliances.', icon: AlertTriangle, action: 'Record Violation' },
  reports: { title: 'Reports', description: 'Access digital inspection and compliance reports.', icon: FileBarChart, action: 'Create Report' },
  search: { title: 'Search & History', description: 'Search previous inspections, products, businesses, and reports.', icon: History },
  notifications: { title: 'Notifications', description: 'Stay up to date with reviews, assignments, and status changes.', icon: Bell },
  settings: { title: 'Settings', description: 'Configure workspace preferences and department settings.', icon: Settings, action: 'Open Settings' },
}

export function DashboardPage() { return <><PageHeader eyebrow="Department workspace" title="Good morning, Arjun." description="Here is the current overview of inspection activity across your department." action={<div className="header-actions"><button className="button button-ghost"><FileSearch size={16} /> Export view</button><Link className="button button-primary" to="/inspections"><ClipboardCheck size={16} /> New inspection</Link></div>} /><div className="stat-grid"><StatCard label="Total inspections" value="1,284" change="↑ 12.4% this month" icon={ClipboardCheck} /><StatCard label="Potential non-compliances" value="86" change="14 need review" icon={AlertTriangle} tone="amber" /><StatCard label="Confirmed violations" value="24" change="↓ 6.2% this month" icon={ShieldCheck} tone="red" /><StatCard label="Compliant products" value="742" change="57.8% of records" icon={Package} tone="green" /><StatCard label="Pending reviews" value="31" change="Across 8 offices" icon={History} tone="amber" /><StatCard label="Laboratory reports" value="118" change="9 received this week" icon={FlaskConical} /></div><div className="dashboard-grid"><ChartCard title="Inspections over time" type="bars" /><ChartCard title="Compliance status" type="donut" /><ChartCard title="Violations by rule" type="rows" /><ChartCard title="Inspections by office" type="office" /></div><section className="dashboard-table"><div className="table-heading"><div><p className="eyebrow">Recent activity</p><h2>Latest inspections</h2></div><Link className="text-link" to="/inspections">View all <span>→</span></Link></div><DataTable headers={['Inspection ID', 'Business', 'Office', 'Date', 'Status']}><tr><td><strong>LM-2026-0184</strong></td><td>Shakti Foods Pvt. Ltd.</td><td>Central Office</td><td>18 Sep 2026</td><td><StatusBadge status="Under Review" /></td></tr><tr><td><strong>LM-2026-0183</strong></td><td>Navya Retail Group</td><td>North Division</td><td>17 Sep 2026</td><td><StatusBadge status="Completed" /></td></tr><tr><td><strong>LM-2026-0182</strong></td><td>Harvest Mills</td><td>East Division</td><td>17 Sep 2026</td><td><StatusBadge status="Requires Verification" /></td></tr></DataTable></section></> }

function ChartCard({ title, type }: { title: string; type: string }) { return <section className="chart-card"><div className="chart-heading"><h3>{title}</h3><button className="icon-button" aria-label={`More ${title} options`}>•••</button></div>{type === 'bars' && <div className="bar-chart"><div className="y-axis"><span>120</span><span>80</span><span>40</span><span>0</span></div><div className="bars">{[48, 71, 60, 86, 68, 92, 78, 100, 82, 76, 94, 88].map((height, index) => <div className="bar-group" key={index}><i style={{ height: `${height}%` }} /><small>{['O', 'N', 'D', 'J', 'F', 'M', 'A', 'M', 'J', 'J', 'A', 'S'][index]}</small></div>)}</div></div>}{type === 'donut' && <div className="donut-wrap"><div className="donut"><div><strong>1,284</strong><small>Total</small></div></div><div className="legend"><span><i className="legend-green" />Compliant <b>58%</b></span><span><i className="legend-amber" />Pending <b>27%</b></span><span><i className="legend-red" />Violation <b>15%</b></span></div></div>}{type === 'rows' && <div className="rule-list">{[['Quantity declaration', '34', 'blue'], ['Net content', '27', 'amber'], ['Pack date', '18', 'green'], ['Consumer care', '12', 'red']].map(([name, count, tone]) => <div className="rule-row" key={name}><span>{name}</span><div><i className={`rule-${tone}`} style={{ width: `${Number(count) * 2.2}%` }} /></div><strong>{count}</strong></div>)}</div>}{type === 'office' && <div className="office-list">{[['Central Office', '428'], ['North Division', '312'], ['East Division', '286'], ['South Division', '258']].map(([name, count]) => <div className="office-row" key={name}><span className="office-avatar">{name.slice(0, 1)}</span><span>{name}</span><strong>{count}</strong></div>)}</div>}</section> }

export function ModulePage({ module }: { module: string }) { const config = moduleConfig[module] ?? moduleConfig.search; const Icon = config.icon; return <><PageHeader eyebrow="Department workspace" title={config.title} description={config.description} action={config.action && <button className="button button-primary"><Icon size={16} /> {config.action}</button>} /><div className="toolbar"><SearchBar placeholder={`Search ${config.title.toLowerCase()}...`} /><FilterBar /></div><div className="module-panel"><EmptyState icon={Icon} title={`No ${config.title.toLowerCase()} yet`} description="This workspace is ready for records when the connected module is enabled." action={config.action} /></div></> }

export function PublicServicesPage() { return <><PageHeader eyebrow="Public services" title="Public services" description="Access public-facing Legal Metrology services. Backend functionality will be connected in a later stage." /><div className="service-placeholder-grid">{['Certificate Verification', 'Application Status', 'Complaint / Grievance', 'Public Information'].map((title) => <div className="service-placeholder" key={title}><FileSearch size={20} /><h3>{title}</h3><p>Placeholder service page ready for future integration.</p><button className="button button-ghost">Open service</button></div>)}</div></> }
