import { useEffect, useState } from 'react'
import { AlertTriangle, Bell, Building2, ClipboardCheck, FileBarChart, FileSearch, FlaskConical, History, Package, ScanLine, Search, Settings, ShieldCheck, Store, Users } from 'lucide-react'
import { Link } from 'react-router-dom'
import { DataTable } from '../components/common/DataTable'
import { EmptyState, FilterBar, LoadingState, PageHeader, SearchBar, StatusBadge } from '../components/common/Ui'
import { StatCard } from '../components/common/StatCard'
import { useAuth } from '../context/AuthContext'
import { supabase as configuredSupabase } from '../services/supabase'

const supabase = configuredSupabase as any
const moduleConfig: Record<string, { title: string; description: string; icon: React.ElementType; action?: string }> = {
  settings: { title: 'Settings', description: 'Configure workspace preferences and department settings.', icon: Settings, action: 'Open Settings' },
  documents: { title: 'Documents', description: 'Review documents available within your permitted workspace.', icon: FileSearch },
  'assigned-samples': { title: 'Assigned Samples', description: 'Review samples assigned to your laboratory.', icon: FlaskConical },
}

type Metrics = { inspections: number; businesses: number; products: number; violations: number; reports: number; pending: number; recent: any[] }
function countResult(result: any) { return result?.count ?? 0 }
function formatCount(value: number) { return new Intl.NumberFormat('en-IN').format(value) }

export function DashboardPage() {
  const auth = useAuth(); const [metrics, setMetrics] = useState<Metrics | null>(null); const [error, setError] = useState<string | null>(null)
  useEffect(() => { let active = true; const load = async () => { if (!supabase) { setError('Supabase is not configured for this environment.'); return }; const [inspections, businesses, products, violations, reports, pending, recent] = await Promise.all([supabase.from('inspections').select('id', { count: 'exact', head: true }), supabase.from('businesses').select('id', { count: 'exact', head: true }), supabase.from('products').select('id', { count: 'exact', head: true }), supabase.from('violations').select('id', { count: 'exact', head: true }), supabase.from('reports').select('id', { count: 'exact', head: true }), supabase.from('compliance_checks').select('id', { count: 'exact', head: true }).eq('status', 'Pending Review'), supabase.from('inspections').select('id, inspection_number, inspection_date, status, businesses(legal_name), offices(office_name)').order('inspection_date', { ascending: false }).limit(5)]); if (!active) return; const failed = [inspections, businesses, products, violations, reports, pending, recent].find((result) => result.error); if (failed) setError('Some dashboard records could not be loaded. Check your connection or permissions.'); setMetrics({ inspections: countResult(inspections), businesses: countResult(businesses), products: countResult(products), violations: countResult(violations), reports: countResult(reports), pending: countResult(pending), recent: recent.data ?? [] }) }; void load(); return () => { active = false } }, [])
  const firstName = auth.profile?.full_name?.split(' ')[0] ?? 'there'
  if (!metrics) return <><PageHeader eyebrow="Department workspace" title={`Good morning, ${firstName}.`} description="Loading permitted records from the connected workspace." /><LoadingState />{error && <div className="inline-error">{error}</div>}</>
  return <><PageHeader eyebrow="Department workspace" title={`Good morning, ${firstName}.`} description="Live overview across the records available to your account." action={<div className="header-actions"><button className="button button-ghost"><FileSearch size={16} /> Export view</button><Link className="button button-primary" to="/inspections/new"><ClipboardCheck size={16} /> New inspection</Link></div>} />{error && <div className="inline-error">{error}</div>}<div className="stat-grid"><StatCard label="Total inspections" value={formatCount(metrics.inspections)} change="From permitted inspection records" icon={ClipboardCheck} /><StatCard label="Registered businesses" value={formatCount(metrics.businesses)} change="From business records" icon={Building2} tone="blue" /><StatCard label="Products" value={formatCount(metrics.products)} change="From product records" icon={Package} tone="green" /><StatCard label="Violations" value={formatCount(metrics.violations)} change="Officer-reviewed records" icon={AlertTriangle} tone="red" /><StatCard label="Pending reviews" value={formatCount(metrics.pending)} change="Compliance checks awaiting review" icon={History} tone="amber" /><StatCard label="Reports" value={formatCount(metrics.reports)} change="Generated report records" icon={FileBarChart} /></div><section className="dashboard-table"><div className="table-heading"><div><p className="eyebrow">Recent activity</p><h2>Latest inspections</h2></div><Link className="text-link" to="/inspections">View all <span>→</span></Link></div>{metrics.recent.length === 0 ? <EmptyState icon={ClipboardCheck} title="No inspections recorded" description="Permitted inspection records will appear here when available." /> : <DataTable headers={['Inspection ID', 'Business', 'Office', 'Date', 'Status']}>{metrics.recent.map((item: any) => <tr key={item.id}><td><Link className="table-link" to={`/inspections/${item.id}`}>{item.inspection_number}</Link></td><td>{item.businesses?.legal_name ?? '—'}</td><td>{item.offices?.office_name ?? '—'}</td><td>{item.inspection_date ? new Date(item.inspection_date).toLocaleDateString() : '—'}</td><td><StatusBadge status={item.status === 'completed' || item.status === 'closed' ? 'Completed' : item.status === 'cancelled' ? 'Inactive' : 'Pending'} /></td></tr>)}</DataTable>}</section></>
}

export function ModulePage({ module }: { module: string }) { const config = moduleConfig[module] ?? { title: module, description: 'This workspace is available to authorized users.', icon: Search }; const Icon = config.icon; return <><PageHeader eyebrow="Workspace" title={config.title} description={config.description} action={config.action && <button className="button button-primary"><Icon size={16} /> {config.action}</button>} /><div className="toolbar"><SearchBar placeholder={`Search ${config.title.toLowerCase()}...`} /><FilterBar /></div><div className="module-panel"><EmptyState icon={Icon} title={`No ${config.title.toLowerCase()} records`} description="No permitted records are available for this workspace." /></div></> }

export function PublicServicesPage() { return <><PageHeader eyebrow="Public services" title="Public services" description="Access public-facing Legal Metrology services." /><div className="service-placeholder-grid">{['Certificate Verification', 'Application Status', 'Complaint / Grievance', 'Public Information'].map((title) => <div className="service-placeholder" key={title}><FileSearch size={20} /><h3>{title}</h3><p>Service availability will be shown when the public integration is connected.</p><button className="button button-ghost" disabled>Unavailable</button></div>)}</div></> }
