import { ArrowRight, ChevronDown, Menu, ShieldCheck } from 'lucide-react'
import { Link } from 'react-router-dom'
import { FeatureVisual } from '../components/layout/FeatureVisual'
import { AboutSection, FeaturesSection, ServicesSection, WorkflowSection } from '../components/public/PublicSections'

export function LandingPage() { return <div className="public-site"><header className="public-header"><Link className="public-brand" to="/"><span className="brand-mark"><ShieldCheck size={19} /></span><span><strong>Legal Metrology</strong><small>Compliance & inspection</small></span></Link><nav className="public-nav"><a href="#about">About System</a><a href="#features">Features</a><a href="#workflow">How It Works</a><a href="#services">Public Services</a></nav><Link className="button button-dark header-login" to="/login">Login <ArrowRight size={15} /></Link><button className="public-menu" aria-label="Open navigation"><Menu size={21} /></button></header><main><section className="hero"><div className="hero-copy"><div className="section-kicker">Government inspection workspace</div><h1>Better records.<br /><em>Stronger trust.</em></h1><p>A digital platform for inspection management, packaged commodity compliance checking, laboratory records, violation management, and digital reporting.</p><div className="hero-actions"><Link className="button button-dark" to="/login">Department Login <ArrowRight size={16} /></Link><Link className="button button-light" to="/login">Business Login</Link><a className="text-link" href="#services">Public Services <ArrowRight size={15} /></a></div><div className="hero-meta"><span><ShieldCheck size={16} /> Officer-led verification</span><span><ChevronDown size={16} /> Connected inspection history</span></div></div><FeatureVisual /></section><AboutSection /><FeaturesSection /><WorkflowSection /><ServicesSection /><section className="closing-cta"><div><div className="section-kicker">Ready when your department is</div><h2>Bring clarity to every inspection.</h2></div><Link className="button button-dark" to="/login">Enter the portal <ArrowRight size={16} /></Link></section></main><footer className="public-footer"><span>© 2026 Legal Metrology Department</span><span>Digital public service foundation</span></footer></div> }

export function LoginPage() { return <div className="login-page"><div className="login-brand"><Link className="public-brand" to="/"><span className="brand-mark"><ShieldCheck size={19} /></span><span><strong>Legal Metrology</strong><small>Compliance & inspection</small></span></Link><p>Choose the workspace that matches your role.</p></div><div className="login-options"><LoginOption title="Department / Government Login" description="For authorised department teams managing offices, inspections, compliance reviews, and records." users="Super Admin · Controller · Inspector · Office Staff · Laboratory User" path="/login/department" icon={ShieldCheck} label="Department Login" /><LoginOption title="Business Login" description="For manufacturers, packers, importers, dealers, and retailers managing their business records." users="Manufacturer · Packer · Importer · Dealer / Retailer" path="/login/business" icon={Building2Icon} label="Business Login" /></div><Link className="back-link" to="/">← Return to public site</Link></div> }
function Building2Icon(props: { size?: number }) { return <span className="building-icon" {...props}>◈</span> }
function LoginOption({ title, description, users, path, icon: Icon, label }: { title: string; description: string; users: string; path: string; icon: React.ElementType; label: string }) { return <article className="login-option"><div className="login-option-icon"><Icon size={22} /></div><h2>{title}</h2><p>{description}</p><small>{users}</small><Link className="button button-dark" to={path}>{label} <ArrowRight size={16} /></Link></article> }
