import { Navigate, Route, Routes } from 'react-router-dom'
import { AuthProvider } from './context/AuthContext'
import { ProtectedRoute, RoleRoute } from './components/auth/ProtectedRoute'
import { AppShell } from './components/layout/AppShell'
import { DashboardPage, ModulePage, PublicServicesPage } from './pages/Portal'
import { LandingPage, LoginPage, NotFoundPage } from './pages/Public'
import { AccountStatePage, BusinessRegistrationPage, ForgotPasswordPage, LoginFormPage, ProfilePage, ResetPasswordPage } from './pages/AuthPages'
import { UsersPage } from './pages/Users'
import { EditOfficePage, InviteOfficerPage, NewOfficePage, OfficeDetailsPage, OfficersPage, OfficerDetailsPage, OfficesPage } from './pages/Government'
import { BusinessApplicationsPage, BusinessDashboardPage, BusinessDetailsPage, BusinessesPage, EditBusinessPage, NewBusinessApplicationPage, NewBusinessPage } from './pages/Business'
import { EditProductPage, NewProductPage, ProductDetailsPage, ProductsPage } from './pages/Product'
import { InspectionDetailsPage, InspectionsPage, NewInspectionPage } from './pages/Inspection'
import { OcrPage } from './pages/Ocr'
import { CompliancePage, ComplianceRunPage, ComplianceRulesPage } from './pages/Compliance'
import { DispatchSamplePage, LaboratoriesPage, LaboratoryDetailsPage, NewSamplePage, SampleDetailsPage, SamplesPage } from './pages/Laboratory'
import { CreateViolationPage, ViolationDetailsPage, ViolationsPage } from './pages/Violation'
import { NewReportPage, ReportDetailsPage, ReportsPage } from './pages/Reports'
import { AuditLogPage } from './pages/AuditLog'
import { SearchPage } from './pages/Search'
import { NotificationsPage } from './pages/Notifications'
import { ArchitecturePage, DeploymentChecklistPage, HelpPage, ProjectInfoPage, SystemStatusPage } from './pages/Documentation'

function PortalRoute({ children, roles }: { children: React.ReactNode; roles?: import('./types/auth').Role[] }) { return <ProtectedRoute roles={roles}><AppShell>{children}</AppShell></ProtectedRoute> }

export default function App() {
	const businessRoles: import('./types/auth').Role[] = ['manufacturer', 'packer', 'importer', 'dealer', 'retailer']
	const governmentRoles: import('./types/auth').Role[] = ['super_admin', 'controller', 'assistant_controller', 'inspector', 'clerk']
	return <AuthProvider><Routes>
		<Route path="/" element={<LandingPage />} /><Route path="/login" element={<LoginPage />} /><Route path="/login/admin" element={<LoginFormPage type="admin" />} /><Route path="/login/department" element={<LoginFormPage type="government" />} /><Route path="/login/business" element={<LoginFormPage type="business" />} />
		<Route path="/access-denied" element={<AccountStatePage state="denied" />} /><Route path="/account-inactive" element={<AccountStatePage state="inactive" />} /><Route path="/account-pending" element={<AccountStatePage state="pending" />} /><Route path="/public-services" element={<PublicServicesPage />} />
		<Route path="/profile" element={<PortalRoute><ProfilePage /></PortalRoute>} /><Route path="/dashboard" element={<PortalRoute><DashboardPage /></PortalRoute>} />
		<Route path="/dashboard/admin" element={<RoleRoute roles={['super_admin']}><AppShell><DashboardPage /></AppShell></RoleRoute>} /><Route path="/dashboard/controller" element={<RoleRoute roles={['controller']}><AppShell><DashboardPage /></AppShell></RoleRoute>} /><Route path="/dashboard/assistant-controller" element={<RoleRoute roles={['assistant_controller']}><AppShell><DashboardPage /></AppShell></RoleRoute>} /><Route path="/dashboard/inspector" element={<RoleRoute roles={['inspector']}><AppShell><DashboardPage /></AppShell></RoleRoute>} /><Route path="/dashboard/clerk" element={<RoleRoute roles={['clerk']}><AppShell><DashboardPage /></AppShell></RoleRoute>} /><Route path="/dashboard/laboratory" element={<RoleRoute roles={['laboratory_user']}><AppShell><DashboardPage /></AppShell></RoleRoute>} /><Route path="/dashboard/business" element={<RoleRoute roles={businessRoles}><AppShell><BusinessDashboardPage /></AppShell></RoleRoute>} />
		<Route path="/business-portal" element={<PortalRoute roles={businessRoles}><BusinessesPage /></PortalRoute>} /><Route path="/businesses" element={<PortalRoute roles={[...governmentRoles, ...businessRoles]}><BusinessesPage /></PortalRoute>} /><Route path="/businesses/new" element={<PortalRoute roles={['super_admin', 'controller', 'assistant_controller', 'clerk']}><NewBusinessPage /></PortalRoute>} /><Route path="/businesses/:businessId/edit" element={<PortalRoute roles={['super_admin', 'controller', 'assistant_controller', 'clerk']}><EditBusinessPage /></PortalRoute>} /><Route path="/businesses/:businessId" element={<PortalRoute roles={[...governmentRoles, ...businessRoles]}><BusinessDetailsPage /></PortalRoute>} />
		<Route path="/business-applications" element={<PortalRoute roles={[...governmentRoles, ...businessRoles]}><BusinessApplicationsPage /></PortalRoute>} /><Route path="/business-applications/new" element={<PortalRoute roles={businessRoles}><NewBusinessApplicationPage /></PortalRoute>} />
		<Route path="/products" element={<PortalRoute roles={[...governmentRoles, ...businessRoles]}><ProductsPage /></PortalRoute>} /><Route path="/products/new" element={<PortalRoute roles={['super_admin', 'controller', 'assistant_controller', 'clerk', ...businessRoles]}><NewProductPage /></PortalRoute>} /><Route path="/products/:productId/edit" element={<PortalRoute roles={['super_admin', 'controller', 'assistant_controller', 'clerk', ...businessRoles]}><EditProductPage /></PortalRoute>} /><Route path="/products/:productId" element={<PortalRoute roles={[...governmentRoles, ...businessRoles]}><ProductDetailsPage /></PortalRoute>} />
		<Route path="/inspections" element={<PortalRoute roles={[...governmentRoles, ...businessRoles]}><InspectionsPage /></PortalRoute>} /><Route path="/inspections/new" element={<PortalRoute roles={['super_admin', 'controller', 'assistant_controller', 'inspector', 'clerk']}><NewInspectionPage /></PortalRoute>} /><Route path="/inspections/:inspectionId" element={<PortalRoute roles={[...governmentRoles, ...businessRoles]}><InspectionDetailsPage /></PortalRoute>} />
		<Route path="/ocr" element={<PortalRoute roles={['super_admin', 'controller', 'assistant_controller', 'inspector', 'clerk']}><OcrPage /></PortalRoute>} />
		<Route path="/inspections/:inspectionId/ocr" element={<PortalRoute roles={['super_admin', 'controller', 'assistant_controller', 'inspector', 'clerk']}><OcrPage /></PortalRoute>} />
		<Route path="/compliance" element={<PortalRoute roles={[...governmentRoles, ...businessRoles]}><CompliancePage /></PortalRoute>} /><Route path="/inspections/:inspectionId/compliance" element={<PortalRoute roles={['super_admin', 'controller', 'assistant_controller', 'inspector', 'clerk']}><ComplianceRunPage /></PortalRoute>} /><Route path="/compliance/rules" element={<PortalRoute roles={governmentRoles}><ComplianceRulesPage /></PortalRoute>} />
		<Route path="/samples" element={<PortalRoute roles={[...governmentRoles, ...businessRoles]}><SamplesPage /></PortalRoute>} /><Route path="/samples/new" element={<PortalRoute roles={['super_admin', 'controller', 'assistant_controller', 'inspector', 'clerk']}><NewSamplePage /></PortalRoute>} /><Route path="/samples/:sampleId/dispatch" element={<PortalRoute roles={['super_admin', 'controller', 'assistant_controller', 'inspector', 'clerk']}><DispatchSamplePage /></PortalRoute>} /><Route path="/samples/:sampleId" element={<PortalRoute roles={[...governmentRoles, ...businessRoles]}><SampleDetailsPage /></PortalRoute>} /><Route path="/laboratory" element={<PortalRoute roles={['super_admin', 'controller', 'assistant_controller', 'laboratory_user']}><LaboratoriesPage /></PortalRoute>} /><Route path="/laboratory/:laboratoryId" element={<PortalRoute roles={['super_admin', 'controller', 'assistant_controller', 'laboratory_user']}><LaboratoryDetailsPage /></PortalRoute>} />
		<Route path="/violations" element={<PortalRoute roles={[...governmentRoles, ...businessRoles]}><ViolationsPage /></PortalRoute>} /><Route path="/violations/new" element={<PortalRoute roles={['super_admin', 'controller', 'assistant_controller', 'inspector', 'clerk']}><CreateViolationPage /></PortalRoute>} /><Route path="/violations/:violationId" element={<PortalRoute roles={[...governmentRoles, ...businessRoles]}><ViolationDetailsPage /></PortalRoute>} />
		<Route path="/reports" element={<PortalRoute roles={[...governmentRoles, ...businessRoles]}><ReportsPage /></PortalRoute>} /><Route path="/reports/new" element={<PortalRoute roles={['super_admin', 'controller', 'assistant_controller', 'inspector', 'clerk']}><NewReportPage /></PortalRoute>} /><Route path="/reports/:reportId" element={<PortalRoute roles={[...governmentRoles, ...businessRoles]}><ReportDetailsPage /></PortalRoute>} />
		<Route path="/search" element={<PortalRoute roles={[...governmentRoles, ...businessRoles]}><SearchPage /></PortalRoute>} />
		<Route path="/search/audit" element={<PortalRoute roles={['super_admin', 'controller', 'assistant_controller']}><AuditLogPage /></PortalRoute>} />
		<Route path="/notifications" element={<PortalRoute><NotificationsPage /></PortalRoute>} />
		<Route path="/help" element={<HelpPage />} /><Route path="/about" element={<ProjectInfoPage />} /><Route path="/architecture" element={<ArchitecturePage />} /><Route path="/deployment" element={<DeploymentChecklistPage />} /><Route path="/system-status" element={<RoleRoute roles={['super_admin']}><AppShell><SystemStatusPage /></AppShell></RoleRoute>} />
		<Route path="/users" element={<RoleRoute roles={['super_admin', 'controller']}><AppShell><UsersPage /></AppShell></RoleRoute>} /><Route path="/offices" element={<PortalRoute roles={governmentRoles}><OfficesPage /></PortalRoute>} /><Route path="/offices/new" element={<PortalRoute roles={['super_admin']}><NewOfficePage /></PortalRoute>} /><Route path="/offices/:officeId/edit" element={<PortalRoute roles={['super_admin']}><EditOfficePage /></PortalRoute>} /><Route path="/offices/:officeId" element={<PortalRoute roles={governmentRoles}><OfficeDetailsPage /></PortalRoute>} /><Route path="/officers" element={<PortalRoute roles={governmentRoles}><OfficersPage /></PortalRoute>} /><Route path="/officers/new" element={<PortalRoute roles={['super_admin']}><InviteOfficerPage /></PortalRoute>} /><Route path="/officers/:officerId" element={<PortalRoute roles={governmentRoles}><OfficerDetailsPage /></PortalRoute>} />
		{['settings', 'documents', 'assigned-samples'].map((module) => <Route key={module} path={`/${module}`} element={<PortalRoute><ModulePage module={module} /></PortalRoute>} />)}<Route path="*" element={<NotFoundPage />} />
	</Routes></AuthProvider>
}
