-- Legacy Part 11 compatibility marker.
-- Report tables, policies, storage, numbering, and snapshots are created by
-- the dependency-ordered migration 202609190010_reports.sql.
-- The obsolete pre-dependency implementation was intentionally removed.
